name: watchyourhealth
description: "Technical Assessment for Watch Your Health - Flutter Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.11
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  lottie: ^3.1.2
  json_annotation: ^4.9.0
  http: ^1.4.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  json_serializable: ^6.9.5

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/lottie/
