// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNZLHN_2IKJTA5WDH9Wc84LmgRrmEtXGw',
    appId: '1:350846527974:web:c6fe028a78caf737dbce27',
    messagingSenderId: '350846527974',
    projectId: 'watch-your-health-4ae97',
    authDomain: 'watch-your-health-4ae97.firebaseapp.com',
    storageBucket: 'watch-your-health-4ae97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsw-H1UP3Z70dVpoaLC20C5bBNXSBhYdA',
    appId: '1:350846527974:android:1b380f98135438c9dbce27',
    messagingSenderId: '350846527974',
    projectId: 'watch-your-health-4ae97',
    storageBucket: 'watch-your-health-4ae97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdbM5fxlENf-01csNlFiUtJs7aB5PLJ4',
    appId: '1:350846527974:ios:e179192788a055c3dbce27',
    messagingSenderId: '350846527974',
    projectId: 'watch-your-health-4ae97',
    storageBucket: 'watch-your-health-4ae97.firebasestorage.app',
    iosBundleId: 'com.magesh.watchyourhealth.watchyourhealth',
  );

}